const {db,logAction}=require('./db');
function addColumn(t,c,type){try{db.exec(`ALTER TABLE ${t} ADD COLUMN ${c} ${type}`)}catch(e){}}
function initCollegeTables(){db.exec(`CREATE TABLE IF NOT EXISTS books(id INTEGER PRIMARY KEY AUTOINCREMENT,college_id INTEGER,book_code TEXT NOT NULL,isbn TEXT,title TEXT NOT NULL,author TEXT NOT NULL,publisher TEXT,category TEXT,total_copies INTEGER NOT NULL DEFAULT 1,available_copies INTEGER NOT NULL DEFAULT 1,shelf TEXT,condition TEXT DEFAULT 'Good',created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS book_issues(id INTEGER PRIMARY KEY AUTOINCREMENT,college_id INTEGER,book_id INTEGER NOT NULL,student_id INTEGER NOT NULL,issue_date TEXT NOT NULL,due_date TEXT NOT NULL,return_date TEXT,issue_condition TEXT DEFAULT 'Good',return_condition TEXT,fine REAL DEFAULT 0,status TEXT DEFAULT 'Issued',notes TEXT);CREATE TABLE IF NOT EXISTS fee_structures(id INTEGER PRIMARY KEY AUTOINCREMENT,college_id INTEGER,session TEXT NOT NULL,category TEXT NOT NULL,fee_name TEXT NOT NULL,amount REAL DEFAULT 0,applicable_to TEXT DEFAULT 'All',notes TEXT);CREATE TABLE IF NOT EXISTS fee_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,college_id INTEGER,student_id INTEGER NOT NULL,session TEXT NOT NULL,semester TEXT NOT NULL,fee_name TEXT NOT NULL,amount_due REAL DEFAULT 0,amount_paid REAL DEFAULT 0,payment_date TEXT,mode TEXT,transaction_ref TEXT,status TEXT DEFAULT 'Pending',remarks TEXT,created_at TEXT DEFAULT(datetime('now')));`);addColumn('books','college_id','INTEGER');addColumn('book_issues','college_id','INTEGER');addColumn('fee_structures','college_id','INTEGER');addColumn('fee_payments','college_id','INTEGER');const c=db.prepare('SELECT id FROM colleges ORDER BY id LIMIT 1').get();['books','book_issues','fee_structures','fee_payments'].forEach(t=>db.prepare(`UPDATE ${t} SET college_id=? WHERE college_id IS NULL`).run(c.id));seed(c.id)}
function seed(cid){if(db.prepare('SELECT COUNT(*) c FROM books WHERE college_id=?').get(cid).c===0){let q=db.prepare(`INSERT INTO books(college_id,book_code,isbn,title,author,publisher,category,total_copies,available_copies,shelf) VALUES(?,?,?,?,?,?,?,?,?,?)`);[['LIB-001','9780131103627','The C Programming Language','Brian W. Kernighan','Prentice Hall','Programming',8,8,'L1-A'],['LIB-002','9780132350884','Clean Code','Robert C. Martin','Prentice Hall','Software Engineering',6,6,'L1-B'],['LIB-003','9780262033848','Introduction to Algorithms','Thomas H. Cormen','MIT Press','Algorithms',5,5,'L2-A'],['LIB-004','9780134685991','Effective Java','Joshua Bloch','Addison-Wesley','Java',5,5,'L2-B'],['LIB-005','9781492051367','Learning Python','Mark Lutz',"O'Reilly",'Python',7,7,'L3-A']].forEach(x=>q.run(cid,...x))}}
function books(cid,q=''){let s=`%${q}%`;return db.prepare('SELECT * FROM books WHERE college_id=? AND (title LIKE ? OR author LIKE ? OR book_code LIKE ? OR isbn LIKE ?) ORDER BY title').all(cid,s,s,s,s)}
function issues(cid){return db.prepare(`SELECT bi.*,b.book_code,b.title,s.full_name,s.roll_no FROM book_issues bi JOIN books b ON b.id=bi.book_id JOIN students s ON s.id=bi.student_id WHERE bi.college_id=? ORDER BY bi.id DESC`).all(cid)}
function issueBook(cid,x){let b=db.prepare('SELECT * FROM books WHERE id=? AND college_id=?').get(+x.book_id,cid),s=db.prepare('SELECT * FROM students WHERE id=? AND college_id=?').get(+x.student_id,cid);if(!b||!s)throw Error('Book or student not found');if(b.available_copies<1)throw Error('No available copy');let i=db.prepare(`INSERT INTO book_issues(college_id,book_id,student_id,issue_date,due_date,issue_condition,notes) VALUES(?,?,?,?,?,?,?)`).run(cid,b.id,s.id,x.issue_date||new Date().toISOString().slice(0,10),x.due_date||new Date(Date.now()+12096e5).toISOString().slice(0,10),x.issue_condition||'Good',x.notes||'');db.prepare('UPDATE books SET available_copies=available_copies-1 WHERE id=? AND college_id=?').run(b.id,cid);logAction('BOOK_ISSUED',{issueId:Number(i.lastInsertRowid)},cid);return i}
function returnBook(cid,id,x){let i=db.prepare('SELECT * FROM book_issues WHERE id=? AND college_id=?').get(+id,cid);if(!i||i.status==='Returned')throw Error('Invalid issue record');db.prepare(`UPDATE book_issues SET return_date=?,return_condition=?,fine=?,status='Returned',notes=? WHERE id=? AND college_id=?`).run(x.return_date||new Date().toISOString().slice(0,10),x.return_condition||'Good',Math.max(0,+x.fine||0),x.notes||i.notes,id,cid);db.prepare('UPDATE books SET available_copies=MIN(total_copies,available_copies+1) WHERE id=? AND college_id=?').run(i.book_id,cid);logAction('BOOK_RETURNED',{issueId:+id},cid);return{ok:true}}
function feeChart(cid){return db.prepare('SELECT * FROM fee_structures WHERE college_id=? ORDER BY session DESC,category,fee_name').all(cid)}
function payments(cid,q=''){let s=`%${q}%`;return db.prepare('SELECT fp.*,s.full_name,s.roll_no,s.department FROM fee_payments fp JOIN students s ON s.id=fp.student_id WHERE fp.college_id=? AND (s.full_name LIKE ? OR s.roll_no LIKE ? OR fp.transaction_ref LIKE ?) ORDER BY fp.id DESC').all(cid,s,s,s)}
function addPayment(cid,x){let due=+x.amount_due||0,paid=+x.amount_paid||0,status=paid<=0?'Pending':paid<due?'Partial':'Paid';if(!db.prepare('SELECT id FROM students WHERE id=? AND college_id=?').get(+x.student_id,cid))throw Error('Student not found');let i=db.prepare(`INSERT INTO fee_payments(college_id,student_id,session,semester,fee_name,amount_due,amount_paid,payment_date,mode,transaction_ref,status,remarks) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(cid,+x.student_id,x.session||'2026-27',x.semester||'1st Semester',x.fee_name||'Institute Fee',due,paid,x.payment_date||new Date().toISOString().slice(0,10),x.mode||'Online',x.transaction_ref||'',status,x.remarks||'');logAction('FEE_PAYMENT_RECORDED',{paymentId:Number(i.lastInsertRowid)},cid);return i}
function feeSummary(cid){let x=db.prepare('SELECT COALESCE(SUM(amount_due),0) due,COALESCE(SUM(amount_paid),0) paid,COUNT(*) payments FROM fee_payments WHERE college_id=?').get(cid);return{...x,pending:Math.max(0,x.due-x.paid)}}
module.exports={initCollegeTables,books,issues,issueBook,returnBook,feeChart,payments,addPayment,feeSummary};