const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),url=require('node:url');
const {db,logAction,DEPARTMENTS,DB_PATH,BACKUP_DIR}=require('./db');
const college=require('./college'); college.initCollegeTables();
const PORT=process.env.PORT||3000,ROOT=__dirname;
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'};
const send=(res,s,x)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(x))};
const body=req=>new Promise((ok,no)=>{let x='';req.on('data',c=>x+=c);req.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch(e){no(Error('Invalid JSON body'))}});req.on('error',no)});
function students(q){let c=[],p=[];if(q.search){c.push('(full_name LIKE ? OR roll_no LIKE ? OR email LIKE ? OR enrollment_id LIKE ?)');let s=`%${q.search}%`;p.push(s,s,s,s)}if(q.department){c.push('department=?');p.push(q.department)}if(q.year){c.push('year=?');p.push(+q.year)}if(q.section){c.push('section=?');p.push(q.section)}let w=c.length?'WHERE '+c.join(' AND '):'',page=Math.max(1,+q.page||1),per=Math.min(100,Math.max(1,+q.perPage||20));let total=db.prepare(`SELECT COUNT(*) c FROM students ${w}`).get(...p).c;let rows=db.prepare(`SELECT * FROM students ${w} ORDER BY id DESC LIMIT ? OFFSET ?`).all(...p,per,(page-1)*per);return{rows,total,page,perPage:per}}
function dashboard(){let total=db.prepare('SELECT COUNT(*) c FROM students').get().c,avgCgpa=db.prepare('SELECT ROUND(AVG(cgpa),2) a FROM students').get().a||0,avgAttendance=db.prepare('SELECT ROUND(AVG(attendance),1) a FROM students').get().a||0,low=db.prepare('SELECT COUNT(*) c FROM students WHERE attendance<65').get().c,dept=db.prepare('SELECT department,COUNT(*) count,ROUND(AVG(cgpa),2) avgCgpa FROM students GROUP BY department ORDER BY count DESC').all(),last=db.prepare('SELECT created_at FROM backups ORDER BY id DESC LIMIT 1').get();return{totalStudents:total,departmentCount:DEPARTMENTS.length,avgCgpa,avgAttendance,lowAttendanceCount:low,departments:dept,lastBackupAt:last?.created_at||null,libraryBooks:db.prepare('SELECT COUNT(*) c FROM books').get().c,issuedBooks:db.prepare("SELECT COUNT(*) c FROM book_issues WHERE status='Issued'").get().c,feeSummary:college.feeSummary()}}
async function api(req,res,p,q){
 if(req.method==='GET'&&p==='/api/dashboard')return send(res,200,dashboard());
 if(req.method==='GET'&&p==='/api/departments')return send(res,200,DEPARTMENTS);
 if(req.method==='GET'&&p==='/api/students')return send(res,200,students(q));
 if(req.method==='POST'&&p==='/api/students'){let x=await body(req);try{let i=db.prepare(`INSERT INTO students(full_name,email,roll_no,enrollment_id,department,program,year,section,cgpa,attendance,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(x.full_name,x.email,x.roll_no,x.enrollment_id,x.department,x.program,+x.year,x.section,+x.cgpa,+x.attendance,+x.attendance<65?'Low Attendance':(x.status||'Active'));logAction('STUDENT_CREATED',{id:i.lastInsertRowid});return send(res,201,db.prepare('SELECT * FROM students WHERE id=?').get(i.lastInsertRowid))}catch(e){return send(res,400,{error:e.message})}}
 let sm=p.match(/^\/api\/students\/(\d+)$/);if(req.method==='DELETE'&&sm){db.prepare('DELETE FROM students WHERE id=?').run(+sm[1]);return send(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/books')return send(res,200,college.books(q.search||''));
 if(req.method==='GET'&&p==='/api/issues')return send(res,200,college.issues());
 if(req.method==='POST'&&p==='/api/issues'){try{return send(res,201,college.issueBook(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 let im=p.match(/^\/api\/issues\/(\d+)\/return$/);if(req.method==='POST'&&im){try{return send(res,200,college.returnBook(+im[1],await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='GET'&&p==='/api/fees/chart')return send(res,200,college.feeChart());
 if(req.method==='GET'&&p==='/api/fees/payments')return send(res,200,college.payments(q.search||''));
 if(req.method==='GET'&&p==='/api/fees/summary')return send(res,200,college.feeSummary());
 if(req.method==='POST'&&p==='/api/fees/payments'){try{return send(res,201,college.addPayment(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='GET'&&p==='/api/audit')return send(res,200,db.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT 50').all());
 if(req.method==='GET'&&p==='/api/backups')return send(res,200,db.prepare('SELECT * FROM backups ORDER BY id DESC').all());
 if(req.method==='POST'&&p==='/api/backups'){let x=await body(req),pin=db.prepare('SELECT value FROM settings WHERE key=?').get('backup_pin');if(x.pin!==pin.value)return send(res,401,{error:'Incorrect security PIN'});let ss=db.prepare('SELECT * FROM students').all(),name=`CV_Backup_${Date.now()}.json`,data=JSON.stringify({createdAt:new Date().toISOString(),students:ss},null,2);fs.writeFileSync(path.join(BACKUP_DIR,name),data);let i=db.prepare('INSERT INTO backups(filename,student_count,size_bytes) VALUES(?,?,?)').run(name,ss.length,Buffer.byteLength(data));logAction('BACKUP_CREATED',{name});return send(res,201,db.prepare('SELECT * FROM backups WHERE id=?').get(i.lastInsertRowid))}
 if(req.method==='POST'&&p==='/api/security/verify-pin'){let x=await body(req),pin=db.prepare('SELECT value FROM settings WHERE key=?').get('backup_pin');return send(res,x.pin===pin.value?200:401,{ok:x.pin===pin.value})}
 return send(res,404,{error:'Not found'});
}
function staticFile(req,res,p){let f=path.resolve(ROOT,'.'+(p==='/'?'/index.html':p));if(!f.startsWith(ROOT+path.sep))return res.writeHead(403).end();fs.readFile(f,(e,d)=>{if(e)return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'});res.end(d)})}
http.createServer(async(req,res)=>{let x=url.parse(req.url,true);try{x.pathname.startsWith('/api/')?await api(req,res,x.pathname,x.query):staticFile(req,res,x.pathname)}catch(e){send(res,500,{error:e.message})}}).listen(PORT,()=>console.log(`CampusVault running on ${PORT}; DB ${DB_PATH}`));